### ISSUE TITLE
Is this @abcnews/alternating-case-to-object or alternating-case-to-object or both?

### ISSUE THREAD

**Issue by phocks** [abcnews/alternating-case-to-object#3]
I noticed in @colingourlay 's project this is referenced as `@abcnews/alternating-case-to-object` but in the readme here it is `alternating-case-to-object` so should we update the readme here? Or which is the main npm module? Or is it both?

**Comment by colingourlay** [comment]
`@abcnews/alternating-case-to-object` is the main npm module (since v2.0.0). `alternating-case-to-object` is the last in v1.x.x (and @nathanhoad still owns). We should update the README.
